language: node_js
node_js:
  - 14

services: 
  - docker

script:
  - docker --version
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

  - docker tag udagram-reverseproxy nmhieu0303/udagram-reverseproxy:lastest
  - docker tag udagram-api-feed nmhieu0303/udagram-api-feed:lastest
  - docker tag udagram-api-user nmhieu0303/udagram-api-user:lastest
  - docker tag udagram-frontend nmhieu0303/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nmhieu0303/udagram-reverseproxy:lastest
  - docker push nmhieu0303/udagram-api-feed:lastest
  - docker push nmhieu0303/udagram-api-user:lastest
  - docker push nmhieu0303/udagram-frontend:v1