apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: nmhieu0303/udagram-reverseproxyv2
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


      kubectl get deployment

      kubectl delete service  reverseproxy
      kubectl delete service  backend-feed
      kubectl delete service  backend-user
      kubectl delete service  frontend
      kubectl delete service  publicfrontend
      kubectl delete service  publicreverseproxy
      

      kubectl delete deployment reverseproxy
      kubectl delete deployment backend-feed
      kubectl delete deployment backend-user
      kubectl delete deployment frontend
      kubectl expose deployment frontend --type=LoadBalancer --name=publicfrontend --port=80
      kubectl expose deployment reverseproxy --type=LoadBalancer --name=publicreverseproxy